package mom.service.drl;
dialect  "java"

import mom.entity.factory.stock.FactStockIn
import com.jeesite.common.lang.StringUtils
import mom.service.factory.client.ClientService
import com.jeesite.common.utils.SpringUtils
import mom.entity.factory.client.Client
import mom.service.basic.config.DataValueService
import com.jeesite.common.lang.DateUtils
import java.util.Date;

global FactStockIn factStockIn

//PMC 色纱入库单获取单号
rule "PMC_StockIn_OrderNo"
    when
    then
    if (factStockIn==null) throw new Exception("色纱入库信息不允许为空");
    String clientId=factStockIn.getClientId();
    if (StringUtils.isEmpty(clientId)) throw new Exception("出库客户标识不允许为为空");
    ClientService clientService=SpringUtils.getBean(ClientService.class);
    Client client=clientService.get(clientId);
    if (client==null) throw new Exception("客户不存在，可能已经被删除");
    String clientCode=client.getClientCode();
    if (StringUtils.isEmpty(clientCode)) throw new Exception("客户编号不存在");
    DataValueService dataValueService=SpringUtils.getBean(DataValueService.class);
    factStockIn.setStockInNo(
            String.format(
                    "DX40-%s%s%s"
                    ,clientCode
                    ,DateUtils.formatDate(new Date(),"yyMMdd")
                    ,String.format("%02d",dataValueService.getNextNum("stockInNo"))
                    )
    );
end
