package mom.service.drl;
dialect  "java"

import mom.entity.factory.proofing.FactProofCargo
import com.jeesite.common.lang.StringUtils
import mom.service.factory.client.ClientService
import com.jeesite.common.utils.SpringUtils
import mom.entity.factory.client.Client
import mom.service.basic.config.DataValueService
import com.jeesite.common.lang.DateUtils
import java.util.Date;

global FactProofCargo factProofCargo

rule "RD_Proof_Cargo_Code"
    when
    then
    if (factProofCargo==null) return;
    String clientId=factProofCargo.getClientId();
    if (StringUtils.isEmpty(clientId)) return;
    ClientService clientService=SpringUtils.getBean(ClientService.class);
    if (clientService==null) return;
    Client client=clientService.get(clientId);
    if (client==null) return;
    String clientCode=client.getClientCode();
    if (StringUtils.isEmpty(clientCode)) return;
    DataValueService dataValueService=SpringUtils.getBean(DataValueService.class);
    factProofCargo.setProofCargoCode(
            String.format(
                    "%s%s%s"
                    ,clientCode,DateUtils.formatDate(new Date(),"yyMMdd")
                    ,String.format("%02d",dataValueService.getNextNum("rd_proof_cargo_code"))
            )
    );
end
