package mom.service.drl;
dialect  "java";

import java.util.List;
import java.util.HashMap;
import java.util.Date;
import com.alibaba.fastjson.JSONObject;
import java.util.stream.Collectors;

import java.util.Arrays;
import com.jeesite.common.msg.EmailAddress;
import org.apache.commons.mail.EmailAttachment;
import com.jeesite.common.msg.EmailUtils;
import com.jeesite.common.msg.EmailConfig
import java.util.ArrayList
import com.jeesite.common.lang.DateUtils;

global String subject;
global List emailAttachmentList;
global List imageFileList;
global EmailConfig emailConfig;


rule "rdStockProdReusing"
    when
    then

    if (emailConfig==null) return;


    String html="<html>";

    html+="<style>";
    html+=".headTitle{font-size:18px}.foot_internal{font-size:16px;color:red}.foot_not_replay{font-size:12px;color:#AEAFAD}.td_item_title{font-size:14px;background:gray;border:0;color:white;align-items:center;align-content:center;align-self:center;alignment-baseline:center}.td_item_data{font-size:12px;border:0}.td_item_key{width:80px}.td_item_value{width:100px}.center{flex-direction:column;text-align:center}.left{flex-direction:column;text-align:left}";
    html+="</style>";

    html+="<body>";

    html+="<div class='headTitle'>库存纱再利用</div>";
    html+="<div class='foot_internal'>内部数据，请注意保密</div>";
    html+="<div class='foot_not_replay'>系统邮件，请勿直接回复</div>";
    html+="</body>";

    html+="</html>";

    EmailAddress senderEmailAddress=new EmailAddress("amaxman@163.com","库存纱再利用");
    List<EmailAddress> emailAddressList=Arrays.asList(
        new EmailAddress("amaxman@163.com","库存纱再利用")
    );

    EmailUtils.sendWithImageAtt(
        emailConfig,
        senderEmailAddress,
        emailAddressList,
        subject,
        html,
        emailAttachmentList,
        imageFileList
    );


end