package mom.service.drl;
dialect  "java";


import java.util.List;
import java.util.Date;
import java.util.stream.Collectors;
import java.util.Comparator;

import java.util.Arrays;
import com.jeesite.common.msg.EmailAddress;
import org.apache.commons.mail.EmailAttachment;
import com.jeesite.common.msg.EmailUtils;
import com.jeesite.common.msg.EmailConfig;
import com.jeesite.common.lang.DateUtils;
import java.util.ArrayList;
import com.jeesite.common.lang.StringUtils;
import com.jeesite.common.utils.SpringUtils;
import java.util.Map;
import java.util.HashMap
import mom.service.factory.scada.DyeLotService
import mom.entity.factory.scada.DyeLot;
import com.jeesite.common.mybatis.mapper.query.QueryType
import mom.view.factory.scada.DyeLotXLS;
import com.jeesite.common.utils.excel.ExcelExport
import com.jeesite.common.config.Global;
import com.jeesite.common.idgen.IdGen;
import java.io.File
import org.apache.poi.ss.usermodel.Row
import com.jeesite.common.utils.excel.ExcelExportEx
import org.apache.poi.ss.usermodel.CellStyle
import org.apache.poi.xssf.usermodel.XSSFColor
import org.apache.poi.ss.usermodel.FillPatternType;

global List emailAddressList;
global EmailConfig emailConfig;

rule "sendVatCompletedNotify"
when
then
    Date date=new Date(),beginTime=DateUtils.getOfDayFirst(DateUtils.addDays(date,-1));
    DyeLotService dyeLotService=SpringUtils.getBean(DyeLotService.class);
    DyeLot where=new DyeLot();
    where.sqlMap().getWhere().and("end_time", QueryType.GTE, beginTime);
    where.sqlMap().getWhere().and("end_time", QueryType.LTE, date);
    List<DyeLot> dyeLotList=dyeLotService.findList(where);
    if (dyeLotList==null || dyeLotList.isEmpty()) {
        System.out.println("没有满足条件的下线提醒");
        return;
    }
    dyeLotList=dyeLotList.stream().sorted(Comparator.comparing(DyeLot::getEndTime)).collect(Collectors.toList());
    List<DyeLotXLS> dyeLotXLSList=new ArrayList<>();
    for (DyeLot dyeLot:dyeLotList) {
        if (dyeLot==null) continue;
        DyeLotXLS dyeLotXLS=DyeLotXLS.getInstance(dyeLot);
        if (dyeLotXLS==null) continue;
        if (StringUtils.equalsIgnoreCase("XG",dyeLotXLS.getDyeLot())) {
            dyeLotXLS.setReDye(null);
        }
        dyeLotXLSList.add(dyeLotXLS);
    }
    if (dyeLotXLSList.isEmpty()) {
        System.out.println("没有满足条件的下线提醒");
        return;
    }

    ExcelExportEx excelExport=new ExcelExportEx("下线提醒",DyeLotXLS.class);
    excelExport.setDataList(dyeLotXLSList);


    if (!dyeLotXLSList.isEmpty()) {
        int dataIndex=0;

        while (dataIndex<dyeLotXLSList.size()-1) {
            DyeLotXLS dyeLotXLSRGB=dyeLotXLSList.get(dataIndex);
            dataIndex++;
            Integer r=dyeLotXLSRGB.getDyeRgbR(),g=dyeLotXLSRGB.getDyeRgbG(),b=dyeLotXLSRGB.getDyeRgbB();
            if (r==null || r<0 || g==null || g<0 || b==null || b<0) continue;
            Row rowRGB=excelExport.getSheet().getRow(dataIndex+1);

            CellStyle cellStyleRGB=excelExport.getWorkbook().createCellStyle();
            XSSFColor backgroundColor = new XSSFColor();
            backgroundColor.setRGB(new byte[]
               {
                   r.byteValue(),
                   g.byteValue(),
                   b.byteValue()
               }
            );
           cellStyleRGB.setFillForegroundColor(backgroundColor);
           cellStyleRGB.setFillPattern(FillPatternType.SOLID_FOREGROUND); //设置填充样式为solid;
           excelExport.addCell(rowRGB,11,"").setCellStyle(cellStyleRGB);

        }
    }

    String foldPath=Global.getUserfilesBaseDir("/fileupload/")+DateUtils.formatDate(new Date(),"yyyyMM")+"/";
    File file=new File(foldPath);
    if (!file.exists()) file.mkdirs();
    String filePathXLS= foldPath+ IdGen.nextId()+".xlsx";
    excelExport.writeFile(filePathXLS);

    List<EmailAttachment> emailAttachmentList=new ArrayList<>();
    EmailAttachment emailAttachment=new EmailAttachment();
    emailAttachment.setDescription("下线染缸作业.xlsx");
    emailAttachment.setName("下线染缸作业.xlsx");
    emailAttachment.setPath(filePathXLS);
    emailAttachmentList.add(emailAttachment);

    EmailAddress senderEmailAddress=new EmailAddress("","下线染缸作业");

    if (emailAddressList==null) emailAddressList=new ArrayList();
    emailAddressList.addAll(Arrays.asList(
        new EmailAddress("","")
    ));

    String html="<html>";

    html+="<style>";
    html+=".headTitle{font-size:18px}.foot_internal{font-size:16px;color:red}.foot_not_replay{font-size:12px;color:#AEAFAD}.td_item_title{font-size:14px;background:gray;border:0;color:white;align-items:center;align-content:center;align-self:center;alignment-baseline:center}.td_item_data{font-size:12px;border:0}.td_item_key{width:100px}.td_item_value{width:500px}.center{flex-direction:column;text-align:center}.left{flex-direction:column;text-align:left}";
    html+="</style>";
    html+="<body>";

    html+="<p><span class='foot_internal'>内部数据，请注意保密</span></p>";
    html+="<p><span class='foot_not_replay'>系统邮件，请勿直接回复</span></p>";
    html+="</body>";
    html+="</html>";

    String subject="下线染缸作业";
    String content=html;

    EmailUtils.sendWithAttach(
            emailConfig.getUserId(),
            emailConfig.getUserPassword(),
            emailConfig.getSmtpAddress(),
            emailConfig.getSmtpPort(),
            emailConfig.getSslOnConnect(),
            emailConfig.getSslSmtpPort(),
            senderEmailAddress,
            emailAddressList,
            subject,
            content,
            emailAttachmentList
        );

    File fileXLS=new File(filePathXLS);
    fileXLS.delete();

end