package mom.service.drl;
dialect  "java";

import mom.entity.factory.manufacture.UtilityValue;
import java.util.List;
import java.util.HashMap;
import java.util.Date;
import com.alibaba.fastjson.JSONObject;
import com.alibaba.fastjson.JSONObject
import java.util.stream.Collectors;

import java.util.Arrays;
import com.jeesite.common.msg.EmailAddress;
import org.apache.commons.mail.EmailAttachment;
import com.jeesite.common.msg.EmailUtils;
import com.jeesite.modules.setting.quartz.util.spring.SpringUtils;
import mom.entity.factory.manufacture.UtilityStat;
import mom.service.factory.manufacture.UtilityStatService;

global String subject;
global UtilityStat utilityStat;
global List emailAttachmentList;
global List imageFileList;


rule "UtilityComputer"
    when
    then

    String html="<html>";

	html+="<style>";
	html+=".headTitle{font-size:18px}.foot_internal{font-size:16px;color:red}.foot_not_replay{font-size:12px;color:#AEAFAD}.td_item_title{font-size:14px;background:gray;border:0;color:white;align-items:center;align-content:center;align-self:center;alignment-baseline:center}.td_item_data{font-size:12px;border:0}.td_item_key{width:80px}.td_item_value{width:100px}.center{flex-direction:column;text-align:center}.left{flex-direction:column;text-align:left}";
	html+="</style>";

	html+="<body>";

	html+="<table>";

	html+="<tr>";
	html+="<td colspan='4' class='center'><span class='headTitle'>"+subject+"</td>";
	html+="</tr>";

	html+="<tr>";
    html+="<td class='td_item_title td_item_key center'>项目</td>";
    html+="<td class='td_item_title td_item_value center'>理论值(元/kg)</td>";
    html+="<td class='td_item_title td_item_value center'>实际值(元/kg)</td>";
    html+="<td class='td_item_title td_item_value center'>相差(元/kg)</td>";
    html+="</tr>";

    html+="<tr>";
    html+="<td class='td_item_data center'>水</td>";
    html+=String.format("<td class='td_item_data center'>%.3f</td>",utilityStat.getWaterTheory());
    html+=String.format("<td class='td_item_data center'>%.3f</td>",utilityStat.getWaterReal());
    html+=String.format("<td class='td_item_data center'>%.3f</td>",utilityStat.getWaterTheory()-utilityStat.getWaterReal());
    html+="</tr>";

    html+="<tr>";
    html+="<td class='td_item_data center'>电</td>";
    html+=String.format("<td class='td_item_data center'>%.3f</td>",utilityStat.getEleTheory());
    html+=String.format("<td class='td_item_data center'>%.3f</td>",utilityStat.getEleReal());
    html+=String.format("<td class='td_item_data center'>%.3f</td>",utilityStat.getEleTheory()-utilityStat.getEleReal());
    html+="</tr>";

    html+="<tr>";
    html+="<td class='td_item_data center'>汽</td>";
    html+=String.format("<td class='td_item_data center'>%.3f</td>",utilityStat.getGasTheory());
    html+=String.format("<td class='td_item_data center'>%.3f</td>",utilityStat.getGasReal());
    html+=String.format("<td class='td_item_data center'>%.3f</td>",utilityStat.getGasTheory()-utilityStat.getGasReal());
    html+="</tr>";

    html+="<tr class='left'>";
    html+="<td colspan='4'><span class='foot_internal'>内部数据，请注意保密</td>";
    html+="</tr>";

    html+="<tr class='left'>";
    html+="<td colspan='4'><span class='foot_not_replay'>系统邮件，请勿直接回复</td>";
    html+="</tr>";

    html+="</table>";
    html+="</body>";

    html+="</html>";

    String userId="",userPassword="",smtpAddress="mail.163.com",slSmtpPort="465";
    String smtpPort="25";
    Boolean sslOnConnect=false;
    EmailAddress senderEmailAddress=new EmailAddress("","水电汽汇总统计");
    List<EmailAddress> emailAddressList=Arrays.asList(
        new EmailAddress("","")
    );

    EmailUtils.sendWithImageAtt(
        userId,
        userPassword,
        smtpAddress,
        smtpPort,
        sslOnConnect,
        slSmtpPort,
        senderEmailAddress,
        emailAddressList,
        subject,
        html,
        emailAttachmentList,
        imageFileList
    );


end